-- ==============================================================================
-- SECTION C: DEMO DATA SEED SCRIPT FOR NOWSHERA DIGITAL ATS
-- Run this script in Supabase SQL Editor ONLY AFTER creating the Auth users in Section B.
--
-- This script dynamically looks up the real Auth UUIDs from public.profiles
-- and creates realistic jobs, recruiter assignments, applications, interviews,
-- stage history, recruiter notes, and AI summaries.
-- ==============================================================================

DO $$
DECLARE
  v_admin_id UUID;
  v_recruiter1_id UUID;
  v_recruiter2_id UUID;
  v_cand1_id UUID;
  v_cand2_id UUID;
  v_cand3_id UUID;
  v_cand4_id UUID;
  v_cand5_id UUID;

  v_job1_id UUID := gen_random_uuid();
  v_job2_id UUID := gen_random_uuid();
  v_job3_id UUID := gen_random_uuid();
  v_job4_id UUID := gen_random_uuid();

  v_cv1_id UUID := gen_random_uuid();
  v_cv2_id UUID := gen_random_uuid();
  v_cv3_id UUID := gen_random_uuid();
  v_cv4_id UUID := gen_random_uuid();
  v_cv5_id UUID := gen_random_uuid();

  v_app1_id UUID := gen_random_uuid();
  v_app2_id UUID := gen_random_uuid();
  v_app3_id UUID := gen_random_uuid();
  v_app4_id UUID := gen_random_uuid();
  v_app5_id UUID := gen_random_uuid();
  v_app6_id UUID := gen_random_uuid();
BEGIN
  -- 1. Look up real User IDs generated by Supabase Auth
  SELECT id INTO v_admin_id FROM public.profiles WHERE LOWER(email) = 'admin@nowsheradigital.com';
  SELECT id INTO v_recruiter1_id FROM public.profiles WHERE LOWER(email) = 'ahmad.recruiter@nowsheradigital.com';
  SELECT id INTO v_recruiter2_id FROM public.profiles WHERE LOWER(email) = 'zainab.recruiter@nowsheradigital.com';
  SELECT id INTO v_cand1_id FROM public.profiles WHERE LOWER(email) = 'ali.khan@example.com';
  SELECT id INTO v_cand2_id FROM public.profiles WHERE LOWER(email) = 'sara.ahmed@example.com';
  SELECT id INTO v_cand3_id FROM public.profiles WHERE LOWER(email) = 'hamza.malik@example.com';
  SELECT id INTO v_cand4_id FROM public.profiles WHERE LOWER(email) = 'fatima.noor@example.com';
  SELECT id INTO v_cand5_id FROM public.profiles WHERE LOWER(email) = 'usman.tariq@example.com';

  -- Validation: Verify that all required accounts exist
  IF v_admin_id IS NULL THEN
    RAISE EXCEPTION 'User admin@nowsheradigital.com not found. Please create the Auth users first (see Section B).';
  END IF;
  IF v_recruiter1_id IS NULL OR v_recruiter2_id IS NULL THEN
    RAISE EXCEPTION 'Recruiters (ahmad.recruiter or zainab.recruiter) not found. Please create the Auth users first (see Section B).';
  END IF;
  IF v_cand1_id IS NULL OR v_cand2_id IS NULL OR v_cand3_id IS NULL OR v_cand4_id IS NULL OR v_cand5_id IS NULL THEN
    RAISE EXCEPTION 'One or more candidate users (ali, sara, hamza, fatima, usman) not found. Please create the Auth users first (see Section B).';
  END IF;

  -- 2. Ensure Profile Details and Roles are confirmed
  UPDATE public.profiles SET full_name = 'Admin Manager', role = 'admin' WHERE id = v_admin_id;
  UPDATE public.profiles SET full_name = 'Ahmad Raza', role = 'recruiter' WHERE id = v_recruiter1_id;
  UPDATE public.profiles SET full_name = 'Zainab Bibi', role = 'recruiter' WHERE id = v_recruiter2_id;
  UPDATE public.profiles SET full_name = 'Ali Khan', role = 'candidate', phone = '+92 333 4567890' WHERE id = v_cand1_id;
  UPDATE public.profiles SET full_name = 'Sara Ahmed', role = 'candidate', phone = '+92 334 5678901' WHERE id = v_cand2_id;
  UPDATE public.profiles SET full_name = 'Hamza Malik', role = 'candidate', phone = '+92 335 6789012' WHERE id = v_cand3_id;
  UPDATE public.profiles SET full_name = 'Fatima Noor', role = 'candidate', phone = '+92 336 7890123' WHERE id = v_cand4_id;
  UPDATE public.profiles SET full_name = 'Usman Tariq', role = 'candidate', phone = '+92 337 8901234' WHERE id = v_cand5_id;

  -- 3. Create Fictional Job Postings
  INSERT INTO public.jobs (id, title, department, location, job_type, description, requirements, last_date, openings, filled_openings, status, created_by, created_at)
  VALUES
    (
      v_job1_id,
      'Junior Python Developer',
      'Engineering',
      'Nowshera / Hybrid',
      'Full-time',
      'Join Nowshera Digital to build scalable backend microservices, data processing pipelines, and RESTful APIs using Python, FastAPI, and PostgreSQL.',
      ARRAY[
        'Strong foundational knowledge of Python 3 and Object-Oriented Programming',
        'Experience building RESTful APIs using FastAPI, Flask, or Django',
        'Familiarity with PostgreSQL, relational database modeling, and SQL queries',
        'Basic understanding of Git version control and Docker containers'
      ],
      (CURRENT_DATE + INTERVAL '30 days'),
      2,
      1,
      'open',
      v_admin_id,
      NOW() - INTERVAL '20 days'
    ),
    (
      v_job2_id,
      'Digital Marketing Executive',
      'Marketing',
      'Nowshera On-site',
      'Full-time',
      'Lead digital recruitment and brand campaigns across multi-channel platforms, optimize SEM/SEO performance, and run data-driven analytics.',
      ARRAY[
        '2+ years experience in B2B or digital marketing campaigns',
        'Hands-on expertise in Google Analytics 4, Meta Ads Manager, and SEO tools',
        'Proven track record of improving conversion rates and candidate acquisition'
      ],
      (CURRENT_DATE + INTERVAL '25 days'),
      1,
      0,
      'open',
      v_admin_id,
      NOW() - INTERVAL '18 days'
    ),
    (
      v_job3_id,
      'AI Automation Intern',
      'AI Skool / Labs',
      'Remote',
      'Internship',
      'Explore generative AI workflows, agentic automation, and LLM integrations using Gemini models and n8n webhook pipelines for recruitment automation.',
      ARRAY[
        'Enthusiastic computer science or data science undergraduate',
        'Understanding of prompt engineering, LLM concepts, and API integration',
        'Basic JavaScript/TypeScript or Python scripting skills'
      ],
      (CURRENT_DATE + INTERVAL '40 days'),
      3,
      0,
      'open',
      v_admin_id,
      NOW() - INTERVAL '15 days'
    ),
    (
      v_job4_id,
      'Senior Cloud Systems Architect (Draft)',
      'Infrastructure',
      'Remote',
      'Full-time',
      'Lead cloud infrastructure, container orchestration, and disaster recovery architectures.',
      ARRAY[
        '5+ years experience in Kubernetes, Cloud Run, and Terraform',
        'Deep expertise in high-availability PostgreSQL configurations'
      ],
      (CURRENT_DATE + INTERVAL '60 days'),
      1,
      0,
      'draft',
      v_admin_id,
      NOW() - INTERVAL '5 days'
    )
  ON CONFLICT (id) DO NOTHING;

  -- 4. Assign Recruiters to Jobs
  INSERT INTO public.job_recruiters (job_id, recruiter_id, assigned_at)
  VALUES
    (v_job1_id, v_recruiter1_id, NOW() - INTERVAL '20 days'),
    (v_job2_id, v_recruiter2_id, NOW() - INTERVAL '18 days'),
    (v_job3_id, v_recruiter1_id, NOW() - INTERVAL '15 days'),
    (v_job3_id, v_recruiter2_id, NOW() - INTERVAL '15 days')
  ON CONFLICT (job_id, recruiter_id) DO NOTHING;

  -- 5. Insert CV References in public.cvs
  INSERT INTO public.cvs (id, candidate_id, file_path, file_name, file_size, mime_type, uploaded_at)
  VALUES
    (v_cv1_id, v_cand1_id, v_cand1_id || '/Ali_Khan_CV.pdf', 'Ali_Khan_CV.pdf', 1048576, 'application/pdf', NOW() - INTERVAL '10 days'),
    (v_cv2_id, v_cand2_id, v_cand2_id || '/Sara_Ahmed_CV.pdf', 'Sara_Ahmed_CV.pdf', 1572864, 'application/pdf', NOW() - INTERVAL '9 days'),
    (v_cv3_id, v_cand3_id, v_cand3_id || '/Hamza_Malik_CV.pdf', 'Hamza_Malik_CV.pdf', 838860, 'application/pdf', NOW() - INTERVAL '8 days'),
    (v_cv4_id, v_cand4_id, v_cand4_id || '/Fatima_Noor_CV.pdf', 'Fatima_Noor_CV.pdf', 1258291, 'application/pdf', NOW() - INTERVAL '7 days'),
    (v_cv5_id, v_cand5_id, v_cand5_id || '/Usman_Tariq_CV.pdf', 'Usman_Tariq_CV.pdf', 943718, 'application/pdf', NOW() - INTERVAL '6 days')
  ON CONFLICT (id) DO NOTHING;

  -- Update profiles with their active CV pointer
  UPDATE public.profiles SET current_cv_path = v_cand1_id || '/Ali_Khan_CV.pdf', current_cv_name = 'Ali_Khan_CV.pdf' WHERE id = v_cand1_id;
  UPDATE public.profiles SET current_cv_path = v_cand2_id || '/Sara_Ahmed_CV.pdf', current_cv_name = 'Sara_Ahmed_CV.pdf' WHERE id = v_cand2_id;
  UPDATE public.profiles SET current_cv_path = v_cand3_id || '/Hamza_Malik_CV.pdf', current_cv_name = 'Hamza_Malik_CV.pdf' WHERE id = v_cand3_id;
  UPDATE public.profiles SET current_cv_path = v_cand4_id || '/Fatima_Noor_CV.pdf', current_cv_name = 'Fatima_Noor_CV.pdf' WHERE id = v_cand4_id;
  UPDATE public.profiles SET current_cv_path = v_cand5_id || '/Usman_Tariq_CV.pdf', current_cv_name = 'Usman_Tariq_CV.pdf' WHERE id = v_cand5_id;

  -- 6. Insert Applications across Pipeline Stages
  -- App 1: Ali Khan -> Python Dev (HIRED)
  INSERT INTO public.applications (id, job_id, candidate_id, cv_id, cv_file_path, cv_file_name, status, applied_at, updated_at)
  VALUES (v_app1_id, v_job1_id, v_cand1_id, v_cv1_id, v_cand1_id || '/Ali_Khan_CV.pdf', 'Ali_Khan_CV.pdf', 'hired', NOW() - INTERVAL '10 days', NOW() - INTERVAL '2 days')
  ON CONFLICT (id) DO NOTHING;

  -- App 2: Sara Ahmed -> Python Dev (INTERVIEW)
  INSERT INTO public.applications (id, job_id, candidate_id, cv_id, cv_file_path, cv_file_name, status, applied_at, updated_at)
  VALUES (v_app2_id, v_job1_id, v_cand2_id, v_cv2_id, v_cand2_id || '/Sara_Ahmed_CV.pdf', 'Sara_Ahmed_CV.pdf', 'interview', NOW() - INTERVAL '9 days', NOW() - INTERVAL '3 days')
  ON CONFLICT (id) DO NOTHING;

  -- App 3: Hamza Malik -> Digital Marketing (SHORTLISTED)
  INSERT INTO public.applications (id, job_id, candidate_id, cv_id, cv_file_path, cv_file_name, status, applied_at, updated_at)
  VALUES (v_app3_id, v_job2_id, v_cand3_id, v_cv3_id, v_cand3_id || '/Hamza_Malik_CV.pdf', 'Hamza_Malik_CV.pdf', 'shortlisted', NOW() - INTERVAL '8 days', NOW() - INTERVAL '4 days')
  ON CONFLICT (id) DO NOTHING;

  -- App 4: Fatima Noor -> AI Intern (APPLIED)
  INSERT INTO public.applications (id, job_id, candidate_id, cv_id, cv_file_path, cv_file_name, status, applied_at, updated_at)
  VALUES (v_app4_id, v_job3_id, v_cand4_id, v_cv4_id, v_cand4_id || '/Fatima_Noor_CV.pdf', 'Fatima_Noor_CV.pdf', 'applied', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days')
  ON CONFLICT (id) DO NOTHING;

  -- App 5: Usman Tariq -> AI Intern (OFFER)
  INSERT INTO public.applications (id, job_id, candidate_id, cv_id, cv_file_path, cv_file_name, status, applied_at, updated_at)
  VALUES (v_app5_id, v_job3_id, v_cand5_id, v_cv5_id, v_cand5_id || '/Usman_Tariq_CV.pdf', 'Usman_Tariq_CV.pdf', 'offer', NOW() - INTERVAL '6 days', NOW() - INTERVAL '1 day')
  ON CONFLICT (id) DO NOTHING;

  -- App 6: Ali Khan -> Digital Marketing (WITHDRAWN - Proves Reapplication Rule!)
  -- Candidate withdrew from this job; can apply again in the future because partial index excludes 'withdrawn'.
  INSERT INTO public.applications (id, job_id, candidate_id, cv_id, cv_file_path, cv_file_name, status, applied_at, withdrawn_at, updated_at)
  VALUES (v_app6_id, v_job2_id, v_cand1_id, v_cv1_id, v_cand1_id || '/Ali_Khan_CV.pdf', 'Ali_Khan_CV.pdf', 'withdrawn', NOW() - INTERVAL '12 days', NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days')
  ON CONFLICT (id) DO NOTHING;

  -- 7. Audit Trail in application_stage_history
  INSERT INTO public.application_stage_history (application_id, old_stage, new_stage, changed_by, notes, changed_at)
  VALUES
    (v_app1_id, 'applied', 'applied', v_cand1_id, 'Initial application submitted online.', NOW() - INTERVAL '10 days'),
    (v_app1_id, 'applied', 'shortlisted', v_recruiter1_id, 'Profile matches Python backend requirements.', NOW() - INTERVAL '7 days'),
    (v_app1_id, 'shortlisted', 'interview', v_recruiter1_id, 'Passed initial screening call.', NOW() - INTERVAL '5 days'),
    (v_app1_id, 'interview', 'offer', v_recruiter1_id, 'High score on technical assessment.', NOW() - INTERVAL '3 days'),
    (v_app1_id, 'offer', 'hired', v_recruiter1_id, 'Offer accepted. Welcome to Nowshera Digital!', NOW() - INTERVAL '2 days'),

    (v_app2_id, 'applied', 'applied', v_cand2_id, 'Initial application submitted online.', NOW() - INTERVAL '9 days'),
    (v_app2_id, 'applied', 'shortlisted', v_recruiter1_id, 'Solid project experience in Python & APIs.', NOW() - INTERVAL '6 days'),
    (v_app2_id, 'shortlisted', 'interview', v_recruiter1_id, 'Scheduled 1-hour technical interview round.', NOW() - INTERVAL '3 days'),

    (v_app3_id, 'applied', 'applied', v_cand3_id, 'Initial application submitted online.', NOW() - INTERVAL '8 days'),
    (v_app3_id, 'applied', 'shortlisted', v_recruiter2_id, 'Meets SEO & performance marketing criteria.', NOW() - INTERVAL '4 days'),

    (v_app4_id, 'applied', 'applied', v_cand4_id, 'Initial application submitted online.', NOW() - INTERVAL '5 days'),

    (v_app5_id, 'applied', 'applied', v_cand5_id, 'Initial application submitted online.', NOW() - INTERVAL '6 days'),
    (v_app5_id, 'applied', 'shortlisted', v_recruiter1_id, 'Strong understanding of AI automation and prompt engineering.', NOW() - INTERVAL '4 days'),
    (v_app5_id, 'shortlisted', 'interview', v_recruiter1_id, 'Technical interview conducted.', NOW() - INTERVAL '2 days'),
    (v_app5_id, 'interview', 'offer', v_recruiter1_id, 'Extended offer for AI Automation Intern role.', NOW() - INTERVAL '1 day'),

    (v_app6_id, 'applied', 'applied', v_cand1_id, 'Initial application submitted.', NOW() - INTERVAL '12 days'),
    (v_app6_id, 'applied', 'withdrawn', v_cand1_id, 'Candidate voluntarily withdrew application.', NOW() - INTERVAL '11 days')
  ON CONFLICT DO NOTHING;

  -- 8. Recruiter Private Evaluation Notes
  INSERT INTO public.recruiter_notes (application_id, recruiter_id, note, created_at)
  VALUES
    (v_app1_id, v_recruiter1_id, 'Ali demonstrated solid knowledge of Python async patterns, database indexing, and query optimization.', NOW() - INTERVAL '5 days'),
    (v_app2_id, v_recruiter1_id, 'Sara has strong API architecture understanding. Candidate scheduled for live coding round.', NOW() - INTERVAL '3 days'),
    (v_app3_id, v_recruiter2_id, 'Hamza presented real campaign case studies with verifiable ROI metrics.', NOW() - INTERVAL '4 days')
  ON CONFLICT DO NOTHING;

  -- 9. Scheduled 1-Hour Interviews
  INSERT INTO public.interviews (application_id, recruiter_id, scheduled_time, end_time, location_or_link, created_at)
  VALUES
    (
      v_app2_id,
      v_recruiter1_id,
      NOW() + INTERVAL '2 days' + INTERVAL '10 hours',
      NOW() + INTERVAL '2 days' + INTERVAL '11 hours',
      'https://meet.google.com/nd-python-interview-sara',
      NOW() - INTERVAL '3 days'
    )
  ON CONFLICT DO NOTHING;

  -- 10. AI CV Summaries (Evaluated against Job Requirements)
  INSERT INTO public.ai_summaries (application_id, cv_id, status, short_profile, requirements_found, requirements_not_found, interview_questions, created_at, updated_at)
  VALUES
    (
      v_app1_id,
      v_cv1_id,
      'completed',
      '[
        "Experienced software developer with 3+ years in Python, FastAPI, and PostgreSQL database architecture.",
        "Demonstrated expertise in microservices design, Docker containerization, and RESTful API standards.",
        "Solid track record in writing unit tests and participating in code review workflows."
      ]'::jsonb,
      '[
        "Strong foundational knowledge of Python 3 and Object-Oriented Programming",
        "Experience building RESTful APIs using FastAPI, Flask, or Django",
        "Familiarity with PostgreSQL, relational database modeling, and SQL queries"
      ]'::jsonb,
      '[]'::jsonb,
      '[
        "How do you optimize slow PostgreSQL queries with complex JOIN operations and high write throughput?",
        "Can you describe how you structure asynchronous request pipelines in FastAPI?",
        "What patterns do you recommend for handling idempotency in API webhook endpoints?"
      ]'::jsonb,
      NOW() - INTERVAL '10 days',
      NOW() - INTERVAL '10 days'
    ),
    (
      v_app2_id,
      v_cv2_id,
      'completed',
      '[
        "Talented Python developer with background in backend API services and relational databases.",
        "Hands-on experience with FastAPI, Pydantic data validation, and automated testing.",
        "Enthusiastic collaborator with clean documentation practices."
      ]'::jsonb,
      '[
        "Strong foundational knowledge of Python 3 and Object-Oriented Programming",
        "Experience building RESTful APIs using FastAPI, Flask, or Django",
        "Familiarity with PostgreSQL, relational database modeling, and SQL queries"
      ]'::jsonb,
      '[]'::jsonb,
      '[
        "Walk us through how you manage database migrations safely in production.",
        "How do you handle authentication and token expiry in a stateless API?",
        "Describe a challenge you solved when integrating third-party APIs."
      ]'::jsonb,
      NOW() - INTERVAL '9 days',
      NOW() - INTERVAL '9 days'
    )
  ON CONFLICT (application_id) DO NOTHING;

  -- 11. Email Notification Events (Idempotent Webhook Audit Log)
  INSERT INTO public.email_events (event_type, recipient_email, recipient_name, subject, payload, status, idempotency_key, sent_at)
  VALUES
    (
      'application_received',
      'ali.khan@example.com',
      'Ali Khan',
      'Application Received: Junior Python Developer - Nowshera Digital',
      '{"jobTitle":"Junior Python Developer"}'::jsonb,
      'simulated',
      'app-received-ali-001',
      NOW() - INTERVAL '10 days'
    ),
    (
      'interview_invitation',
      'sara.ahmed@example.com',
      'Sara Ahmed',
      'Interview Invitation: Junior Python Developer - Nowshera Digital',
      '{"scheduledTime":"In 2 days at 10:00 AM"}'::jsonb,
      'simulated',
      'interview-invite-sara-002',
      NOW() - INTERVAL '3 days'
    ),
    (
      'hired',
      'ali.khan@example.com',
      'Ali Khan',
      'Congratulations! Welcome to Nowshera Digital',
      '{"jobTitle":"Junior Python Developer","startDate":"Next Monday"}'::jsonb,
      'simulated',
      'hired-notice-ali-003',
      NOW() - INTERVAL '2 days'
    )
  ON CONFLICT (idempotency_key) DO NOTHING;

  RAISE NOTICE 'Demo data successfully seeded for Nowshera Digital ATS!';
END $$;
